## Ancient WarFare

            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:spawner:*>); 
            mods.jei.JEI.removeAndHide(<ancientwarfare:research_note>); 
            mods.jei.JEI.removeAndHide(<ancientwarfare:steel_ingot>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_arrow>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_arrow_flame>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_arrow_iron>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_arrow_iron_flame>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_ball_shot>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_ballista_bolt>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_ballista_bolt_explosive>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_ballista_bolt_flame>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_ballista_bolt_iron>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_canister_shot_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_canister_shot_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_canister_shot_25>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_canister_shot_5>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_cluster_shot_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_cluster_shot_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_cluster_shot_30>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_cluster_shot_45>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_explosive_shot_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_explosive_shot_10_big>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_explosive_shot_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_explosive_shot_15_big>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_explosive_shot_30>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_explosive_shot_30_big>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_explosive_shot_45>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_explosive_shot_45_big>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_flame_shot_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_flame_shot_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_flame_shot_30>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_flame_shot_45>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_grape_shot_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_grape_shot_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_grape_shot_25>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_grape_shot_5>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_hwacha_rocket>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_hwacha_rocket_airburst>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_hwacha_rocket_explosive>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_hwacha_rocket_flame>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_iron_ball_shot>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_iron_shot_10_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_iron_shot_15_30>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_iron_shot_25_45>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_iron_shot_5_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_napalm_shot_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_napalm_shot_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_napalm_shot_30>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_napalm_shot_45>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_pebble_shot_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_pebble_shot_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_pebble_shot_30>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_pebble_shot_45>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_soldier_arrow_5>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_soldier_arrow_5_flaming>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_soldier_arrow_7>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_soldier_arrow_7_flaming>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_stone_shot_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_stone_shot_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_stone_shot_30>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_stone_shot_45>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_torpedo_10>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_torpedo_15>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_torpedo_30>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ammo_torpedo_45>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:armor_iron>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:armor_obsidian>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:armor_stone>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:clay_casing>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:cluster_charge>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:counter_weight_unit>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:equipment_bay>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:explosive_charge>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:fine_iron>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:flame_charge>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:iron_casing>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:iron_core_wood>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:ironshod_wood>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:major_alloy>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:minor_alloy>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:mobility_unit>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:napalm_charge>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:powder_case>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:rocket_charge>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:rough_iron>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:rough_wood>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:tempered_iron>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:torsion_unit>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:treated_wood>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:turret_components>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:vehicle_upgrade_aim>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:vehicle_upgrade_pitch_down>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:vehicle_upgrade_pitch_up>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:vehicle_upgrade_power>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:vehicle_upgrade_reload>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:vehicle_upgrade_speed>); 
            mods.jei.JEI.removeAndHide(<ancientwarfarevehicle:vehicle_upgrade_turret_pitch>); 
            mods.jei.JEI.removeAndHide(<ancientwarfare:research_note>);
            mods.jei.JEI.removeAndHide(<ancientwarfare:steel_ingot>);
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"amazon", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"barbarian", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"barbarian", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"barbarian", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"barbarian", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"beast", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"beast", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"beast", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"beast", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"brigand", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"buffloka", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"coven", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"coven", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"coven", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"coven", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"coven", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"coven", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"coven", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"coven", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"coven", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"demon", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"dwarf", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"elf", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"empire", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ent", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ent", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ent", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ent", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ent", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ent", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ent", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"evil", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"giant", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"giant", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"giant", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"giant", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gnome", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gnome", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gnome", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gnome", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gnome", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gnome", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gnome", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gnome", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gnome", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"good", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gremlin", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gremlin", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gremlin", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gremlin", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gremlin", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gremlin", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"gremlin", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"guild", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"guild", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"guild", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"guild", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"guild", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"hobbit", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"icelord", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"icelord", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"icelord", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"icelord", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"icelord", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"icelord", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"icelord", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"icelord", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ishtari", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ishtari", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ishtari", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ishtari", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"ishtari", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"klown", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"klown", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"kong", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"lizardman", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"lizardman", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"lizardman", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"lizardman", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"minossian", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"minossian", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"minossian", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"minossian", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"monster", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"monster", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"monster", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"monster", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"nogg", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"norska", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"orc", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"pirate", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"rakshasa", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"rakshasa", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sarkonid", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"sealsker", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"smingol", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"smingol", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"undead", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vampire", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"vyncan", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"witchbane", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"wizardly", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"xoltec", npcType: "faction.trader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.archer.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.bard"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.cavalry"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.civilian.female"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.civilian.male"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.leader"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.leader.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.mounted_archer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.priest"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.siege_engineer"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.soldier"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.soldier.elite"}));
            mods.jei.JEI.hide(<ancientwarfarenpc:npc_spawner>.withTag({npcSubtype: "", faction:"zimba", npcType: "faction.trader"}));