        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "uranium", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "uranium235", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "uuamplifier", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "uumatter", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "vanadium", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "vanadium_gallium", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "vanadium_steel", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "vinegar", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "vinyl_acetate", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "vinyl_chloride", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "vodka", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "water", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "weak_blue_steel", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "weak_red_steel", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "weak_steel", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "whiskey", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "wood_gas", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "wood_tar", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "wood_vinegar", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "wrought_iron", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "ytterbium", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "yttrium", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "yttrium_barium_cuprate", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:815>.withTag({Fluid: {FluidName: "zinc", Amount: 48000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "acetic_acid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "acetone", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "air", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "allyl_chloride", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "aluminium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "americium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "ammonia", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "annealed_copper", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "antimony", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "argon", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "barium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "battery_alloy", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "beer", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "benzene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "beryllium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "bio_diesel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "biomass", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "bismuth", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "bismuth_bronze", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "bisphenol_a", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "black_bronze", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "black_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "blaze", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "blue_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "blue_vitriol_water_solution", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "borosilicate_glass", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "brass", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "brine", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "bronze", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "butadiene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "butane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "butene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "cadmium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "caesium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "calcium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "calcium_acetate", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "carbon", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "carbon_dioxide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "carbon_monoxide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "cerium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "charcoal_byproducts", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "chloramine", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "chlorine", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "chloroform", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "chloromethane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "chrome", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "cider", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "cobalt", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "cobalt_brass", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "concrete", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "construction_foam", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "copper", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "corn_whiskey", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "cracked_heavy_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "cracked_light_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "creosote", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "cumene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "cupronickel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "damascus_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "darmstadtium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "deuterium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "dichlorobenzene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "diluted_hydrochloric_acid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "diluted_sulfuric_acid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "dimethylamine", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "dimethyldichlorosilane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "dimethylhidrazine", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "dinitrogen_tetroxide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "distilled_water", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "drilling_fluid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "duranium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "dysprosium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "electrum", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "epichlorhydrin", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "epoxid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "erbium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "ethane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "ethanol", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "ethenone", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "ethylene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "europium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "fermented_biomass", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "fish_oil", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "fluorine", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "fresh_water", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "gadolinium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "gallium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "gallium_arsenide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "gas", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "glass", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "glowstone", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "glycerol", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "glyceryl", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "gold", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "graphene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "graphite", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "heavy_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "helium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "helium3", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "high_carbon_black_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "high_carbon_blue_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "high_carbon_red_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "high_carbon_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "holmium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "honey", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hot_water", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hsse", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hssg", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hsss", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrochloric_acid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_butadiene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_butane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_butene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_ethane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_ethylene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_gas", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_heavy_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_light_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_naphtha", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_propane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrocracked_propene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrofluoric_acid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrogen", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hydrogen_sulfide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "hypochlorous_acid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "ice", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "indium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "indium_concentrate", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "indium_gallium_phosphide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "invar", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "iridium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "iron", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "iron_magnetic", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "isoprene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "juice", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "kanthal", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "lanthanum", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "lava", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "lead", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "lead_zinc_solution", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "light_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "limewater", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "liquid_air", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "lithium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "lpg", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "lubricant", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "lutetium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "magnalium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "magnesium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "manganese", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "mc_guffium239", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "mercury", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "methane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "methanol", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "methyl_acetate", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "milk", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "milk_curdled", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "milk_vinegar", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "molybdenum", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "naphtha", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "naquadah", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "naquadah_alloy", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "naquadah_enriched", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "naquadria", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "natural_gas", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "neodymium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "neodymium_magnetic", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "neutral_matter", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "neutronium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nichrome", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nickel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nickel_sulfate_water_solution", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nickel_zinc_ferrite", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "niobium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "niobium_nitride", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "niobium_titanium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nitration_mixture", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nitric_acid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nitric_oxide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nitro_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nitrogen", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "nitrogen_dioxide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "noble_gases", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "oil", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "oil_heavy", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "oil_light", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "oil_medium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "olive_oil", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "osmiridium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "osmium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "oxygen", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "palladium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "phenol", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "phosphoric_acid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "pig_iron", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "plasma.argon", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "plasma.helium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "plasma.iron", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "plasma.nickel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "plasma.nitrogen", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "plasma.oxygen", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "plastic", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "platinum", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "plutonium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "plutonium241", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "polycaprolactam", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "polyphenylene_sulfide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "polystyrene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "polytetrafluoroethylene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "polyvinyl_acetate", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "polyvinyl_chloride", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "positive_matter", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potassium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.awkward", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.fire_resistance", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.harming", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.healing", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.invisibility", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.leaping", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_fire_resistance", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_invisibility", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_leaping", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_night_vision", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_poison", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_regeneration", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_slowness", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_strength", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_swiftness", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_water_breathing", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.long_weakness", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.luck", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.mundane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.night_vision", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.poison", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.regeneration", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.slowness", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.strength", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.strong_harming", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.strong_healing", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.strong_leaping", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.strong_poison", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.strong_regeneration", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.strong_strength", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.strong_swiftness", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.swiftness", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.thick", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.water_breathing", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "potion.minecraft.weakness", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "praseodymium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "promethium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "propane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "propene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "radon", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "raw_growth_medium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "red_alloy", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "red_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "redstone", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "reinforced_epoxy_resin", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "rocket_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "rose_gold", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "rubber", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "rubidium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "rum", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "rye_whiskey", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sake", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "salt_water", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "samarium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "scandium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "seed_oil", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "silicon", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "silicon_rubber", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "silicone", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "silver", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sodium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sodium_persulfate", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "soldering_alloy", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "stainless_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steam", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steamcracked_butadiene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steamcracked_butane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steamcracked_butene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steamcracked_ethane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steamcracked_ethylene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steamcracked_gas", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steamcracked_naphtha", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steamcracked_propane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steamcracked_propene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "steel_magnetic", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sterilized_growth_medium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sterling_silver", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "strontium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "styrene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "styrene_butadiene_rubber", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sulfur_dioxide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sulfur_trioxide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sulfuric_acid", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sulfuric_gas", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sulfuric_heavy_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sulfuric_light_fuel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "sulfuric_naphtha", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tannin", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tantalum", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tellurium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "terbium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tetrafluoroethylene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tetranitromethane", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "thorium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "thulium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tin", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tin_alloy", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "titanium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "titanium_tetrachloride", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "toluene", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tritanium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tritium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tungsten", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tungsten_carbide", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "tungsten_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "ultimet", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "unknown", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "uranium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "uranium235", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "uuamplifier", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "uumatter", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "vanadium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "vanadium_gallium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "vanadium_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "vinegar", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "vinyl_acetate", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "vinyl_chloride", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "vodka", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "water", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "weak_blue_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "weak_red_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "weak_steel", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "whiskey", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "wood_gas", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "wood_tar", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "wood_vinegar", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "wrought_iron", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "ytterbium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "yttrium", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "yttrium_barium_cuprate", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:machine:816>.withTag({Fluid: {FluidName: "zinc", Amount: 64000}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "acetic_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "acetone"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "air"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "allyl_chloride"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "aluminium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "americium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "ammonia"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "annealed_copper"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "antimony"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "argon"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "barium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "battery_alloy"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "beer"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "benzene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "beryllium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "bio_diesel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "biomass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "bismuth"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "bismuth_bronze"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "bisphenol_a"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "black_bronze"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "black_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "blaze"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "blue_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "blue_vitriol_water_solution"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "borosilicate_glass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "brass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "brine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "bronze"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "butadiene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "butane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "butene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "cadmium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "caesium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "calcium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "calcium_acetate"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "carbon"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "carbon_dioxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "carbon_monoxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "cerium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "charcoal_byproducts"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "chloramine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "chlorine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "chloroform"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "chloromethane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "chrome"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "cider"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "cobalt"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "cobalt_brass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "concrete"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "construction_foam"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "copper"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "corn_whiskey"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "cracked_heavy_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "cracked_light_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "creosote"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "cumene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "cupronickel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "damascus_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "darmstadtium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "deuterium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "dichlorobenzene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "diluted_hydrochloric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "diluted_sulfuric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "dimethylamine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "dimethyldichlorosilane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "dimethylhidrazine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "dinitrogen_tetroxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "distilled_water"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "drilling_fluid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "duranium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "dysprosium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "electrum"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "epichlorhydrin"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "epoxid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "erbium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "ethane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "ethanol"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "ethenone"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "ethylene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "europium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "fermented_biomass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "fish_oil"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "fluorine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "fresh_water"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "gadolinium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "gallium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "gallium_arsenide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "gas"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "glass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "glowstone"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "glue"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "glycerol"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "glyceryl"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "gold"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "graphene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "graphite"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "heavy_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "helium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "helium3"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "high_carbon_black_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "high_carbon_blue_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "high_carbon_red_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "high_carbon_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "holmium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "honey"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hot_water"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hsse"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hssg"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hsss"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrochloric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_butadiene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_butane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_butene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_ethane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_ethylene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_gas"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_heavy_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_light_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_naphtha"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_propane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrocracked_propene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrofluoric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrogen"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hydrogen_sulfide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "hypochlorous_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "ice"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "indium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "indium_concentrate"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "indium_gallium_phosphide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "invar"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "iridium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "iron"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "iron_magnetic"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "isoprene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "juice"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "kanthal"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "lanthanum"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "lava"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "lead"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "lead_zinc_solution"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "light_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "limewater"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "liquid_air"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "lithium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "lpg"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "lubricant"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "lutetium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "magnalium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "magnesium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "manganese"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "mc_guffium239"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "mercury"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "methane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "methanol"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "methyl_acetate"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "milk"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "milk_curdled"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "milk_vinegar"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "molybdenum"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "naphtha"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "naquadah"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "naquadah_alloy"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "naquadah_enriched"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "naquadria"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "natural_gas"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "neodymium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "neodymium_magnetic"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "neutral_matter"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "neutronium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nichrome"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nickel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nickel_sulfate_water_solution"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nickel_zinc_ferrite"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "niobium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "niobium_nitride"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "niobium_titanium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nitration_mixture"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nitric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nitric_oxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nitro_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nitrogen"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "nitrogen_dioxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "noble_gases"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "oil"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "oil_heavy"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "oil_light"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "oil_medium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "olive_oil"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "osmiridium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "osmium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "oxygen"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "palladium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "phenol"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "phosphoric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "pig_iron"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "plasma.argon"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "plasma.helium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "plasma.iron"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "plasma.nickel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "plasma.nitrogen"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "plasma.oxygen"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "plastic"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "platinum"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "plutonium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "plutonium241"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "polycaprolactam"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "polyphenylene_sulfide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "polystyrene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "polytetrafluoroethylene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "polyvinyl_acetate"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "polyvinyl_chloride"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "positive_matter"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potassium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.awkward"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.fire_resistance"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.harming"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.healing"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.invisibility"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.leaping"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_fire_resistance"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_invisibility"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_leaping"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_night_vision"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_poison"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_regeneration"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_slowness"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_strength"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_swiftness"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_water_breathing"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.long_weakness"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.luck"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.mundane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.night_vision"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.poison"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.regeneration"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.slowness"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.strength"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.strong_harming"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.strong_healing"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.strong_leaping"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.strong_poison"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.strong_regeneration"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.strong_strength"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.strong_swiftness"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.swiftness"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.thick"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.water_breathing"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "potion.minecraft.weakness"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "praseodymium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "promethium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "propane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "propene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "radon"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "raw_growth_medium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "red_alloy"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "red_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "redstone"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "reinforced_epoxy_resin"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "rocket_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "rose_gold"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "rubber"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "rubidium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "rum"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "rye_whiskey"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sake"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "salt_water"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "samarium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "scandium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "seed_oil"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "silicon"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "silicon_rubber"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "silicone"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "silver"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sodium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sodium_persulfate"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "soldering_alloy"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "stainless_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steam"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steamcracked_butadiene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steamcracked_butane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steamcracked_butene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steamcracked_ethane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steamcracked_ethylene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steamcracked_gas"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steamcracked_naphtha"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steamcracked_propane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steamcracked_propene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "steel_magnetic"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sterilized_growth_medium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sterling_silver"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "strontium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "styrene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "styrene_butadiene_rubber"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sulfur_dioxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sulfur_trioxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sulfuric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sulfuric_gas"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sulfuric_heavy_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sulfuric_light_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "sulfuric_naphtha"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tannin"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tantalum"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tellurium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "terbium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tetrafluoroethylene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tetranitromethane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "thorium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "thulium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tin"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tin_alloy"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "titanium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "titanium_tetrachloride"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "toluene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tritanium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tritium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tungsten"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tungsten_carbide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "tungsten_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "ultimet"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "unknown"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "uranium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "uranium235"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "uuamplifier"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "uumatter"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "vanadium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "vanadium_gallium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "vanadium_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "vinegar"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "vinyl_acetate"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "vinyl_chloride"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "vodka"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "water"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "weak_blue_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "weak_red_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "weak_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "whiskey"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "wood_gas"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "wood_tar"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "wood_vinegar"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "wrought_iron"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "ytterbium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "yttrium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "yttrium_barium_cuprate"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32405>.withTag({Fluid: {FluidName: "zinc"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "acetic_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "acetone"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "air"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "allyl_chloride"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "aluminium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "americium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "ammonia"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "annealed_copper"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "antimony"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "argon"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "barium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "battery_alloy"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "beer"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "benzene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "beryllium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "bio_diesel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "biomass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "bismuth"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "bismuth_bronze"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "bisphenol_a"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "black_bronze"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "black_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "blaze"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "blue_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "blue_vitriol_water_solution"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "borosilicate_glass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "brass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "brine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "bronze"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "butadiene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "butane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "butene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "cadmium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "caesium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "calcium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "calcium_acetate"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "carbon"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "carbon_dioxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "carbon_monoxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "cerium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "charcoal_byproducts"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "chloramine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "chlorine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "chloroform"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "chloromethane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "chrome"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "cider"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "cobalt"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "cobalt_brass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "concrete"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "construction_foam"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "copper"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "corn_whiskey"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "cracked_heavy_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "cracked_light_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "creosote"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "cumene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "cupronickel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "damascus_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "darmstadtium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "deuterium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "dichlorobenzene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "diluted_hydrochloric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "diluted_sulfuric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "dimethylamine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "dimethyldichlorosilane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "dimethylhidrazine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "dinitrogen_tetroxide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "distilled_water"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "drilling_fluid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "duranium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "dysprosium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "electrum"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "epichlorhydrin"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "epoxid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "erbium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "ethane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "ethanol"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "ethenone"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "ethylene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "europium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "fermented_biomass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "fish_oil"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "fluorine"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "fresh_water"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "gadolinium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "gallium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "gallium_arsenide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "gas"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "glass"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "glowstone"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "glue"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "glycerol"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "glyceryl"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "gold"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "graphene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "graphite"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "heavy_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "helium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "helium3"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "high_carbon_black_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "high_carbon_blue_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "high_carbon_red_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "high_carbon_steel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "holmium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "honey"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hot_water"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hsse"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hssg"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hsss"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrochloric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_butadiene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_butane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_butene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_ethane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_ethylene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_gas"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_heavy_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_light_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_naphtha"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_propane"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrocracked_propene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrofluoric_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrogen"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hydrogen_sulfide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "hypochlorous_acid"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "ice"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "indium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "indium_concentrate"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "indium_gallium_phosphide"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "invar"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "iridium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "iron"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "iron_magnetic"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "isoprene"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "juice"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "kanthal"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "lanthanum"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "lava"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "lead"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "lead_zinc_solution"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "light_fuel"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "limewater"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "liquid_air"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "lithium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "lpg"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "lubricant"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "lutetium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "magnalium"}}));
        mods.jei.JEI.hide(<gregtech:meta_item_1:32406>.withTag({Fluid: {FluidName: "magnesium"}}));
